version: "3"

services:
        rtmp:
                build:
                        context: ./rtmp
                ports:
                        - 1935:1935
        hls:
                image: jrottenberg/ffmpeg
                volumes:
                        - ./stream:/stream
                command: "-i rtmp://rtmp:1935/live/1234 -hls_time 10 -hls_list_size 6 -hls_wrap 10 -start_number 1 /stream/stream.m3u8"

